version: '3'

services:
    rabbitmq:
        build:
            context: ./rabbitmq
            dockerfile: Dockerfile
        ports:
            - 15672:15672

    openresty:
        build:
            context: ./openresty
            dockerfile: Dockerfile
        ports:
            - 80:80
        depends_on:
            - rabbitmq
